In [2]:
import numpy as np

### Numpy array object

In [12]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [7]:
type(a)

numpy.ndarray

Data type

In [3]:
a.dtype

dtype('int32')

Shape

In [4]:
a.shape

(5,)

Matrix

In [10]:
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [9]:
m.shape

(2, 2)

In [11]:
type(m)

numpy.ndarray

In [13]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

### Selecting elements

In [14]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
a[0, 0]

1

In [16]:
a[0, 1]

2

In [17]:
a[1, 0]

3

In [18]:
a[1, 1]

4

### Data type objects

In [19]:
a.dtype

dtype('int32')

In [21]:
a.dtype.itemsize # Number of bytes

4

Character codes

In [23]:
b = np.arange(7, dtype='d')
b

array([0., 1., 2., 3., 4., 5., 6.])

In [24]:
b.dtype

dtype('float64')

dtype constructors

In [27]:
np.dtype(float)

dtype('float64')

In [28]:
np.dtype('f')

dtype('float32')

In [29]:
np.dtype('d')

dtype('float64')

In [30]:
np.dtype('f8')

dtype('float64')

In [33]:
list(np.sctypeDict.keys())

['?',
 0,
 'byte',
 'b',
 1,
 'ubyte',
 'B',
 2,
 'short',
 'h',
 3,
 'ushort',
 'H',
 4,
 'i',
 5,
 'uint',
 'I',
 6,
 'intp',
 'p',
 9,
 'uintp',
 'P',
 10,
 'long',
 'l',
 7,
 'L',
 8,
 'longlong',
 'q',
 'ulonglong',
 'Q',
 'half',
 'e',
 23,
 'f',
 11,
 'double',
 'd',
 12,
 'longdouble',
 'g',
 13,
 'cfloat',
 'F',
 14,
 'cdouble',
 'D',
 15,
 'clongdouble',
 'G',
 16,
 'O',
 17,
 'S',
 18,
 'unicode',
 'U',
 19,
 'void',
 'V',
 20,
 'M',
 21,
 'm',
 22,
 'bool8',
 'Bool',
 'b1',
 'int64',
 'Int64',
 'i8',
 'uint64',
 'Uint64',
 'u8',
 'float16',
 'Float16',
 'f2',
 'float32',
 'Float32',
 'f4',
 'float64',
 'Float64',
 'f8',
 'complex64',
 'Complex32',
 'c8',
 'complex128',
 'Complex64',
 'c16',
 'object0',
 'Object0',
 'bytes0',
 'Bytes0',
 'str0',
 'Str0',
 'void0',
 'Void0',
 'datetime64',
 'Datetime64',
 'M8',
 'timedelta64',
 'Timedelta64',
 'm8',
 'int32',
 'Int32',
 'i4',
 'uint32',
 'UInt32',
 'u4',
 'UInt64',
 'int16',
 'Int16',
 'i2',
 'uint16',
 'UInt16',
 'u2',
 'int

dtype attributes

In [38]:
t = np.dtype('float64')
t

dtype('float64')

In [41]:
t.type

numpy.float64

In [42]:
t.char

'd'

In [43]:
t.str

'<f8'

record data type

In [44]:
t = np.dtype([
    ('name', np.str_, 40), 
    ('numitems', np.int32), 
    ('price', np.float32)
])

t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [45]:
t['name']

dtype('<U40')

In [46]:
itemz = np.array([
    ('Meaning of life DVD', 42, 3.14), 
    ('Butter', 13, 2.72)
], dtype=t)
itemz

array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)],
      dtype=[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [47]:
itemz[1]

('Butter', 13, 2.72)

### Slicing and indexing

In [48]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
a[3:7]

array([3, 4, 5, 6])

In [50]:
a[:7:2]

array([0, 2, 4, 6])

In [51]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

Multiple dimensions

In [52]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
b.shape

(2, 3, 4)

In [54]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Manipulating array shapes

In [59]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
c = b.ravel() # Returns a view of the array
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
d = b.flatten() # Returns a new memory allocation
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
b[0] = 99

In [70]:
c

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Other operations

In [72]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [74]:
b.shape = (6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [77]:
b.resize((2, 12)) # Changes the array

In [78]:
b 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

### Stacking

In [7]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

Horizontal stacking

In [84]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [87]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

Vertical stacking

In [89]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [90]:
np.concatenate((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

Depth stacking

In [91]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

Column stacking

In [4]:
oned = np.arange(2)
oned

array([0, 1])

In [5]:
twice_oned = 2 * oned
twice_oned

array([0, 2])

In [6]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

Same as hstack()

In [9]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

Row stacking

In [10]:
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

Same as vstack()

In [11]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### Splitting

In [12]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

Horizontal splitting

In [16]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

Same as split()

In [17]:
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

Vertical splitting

In [18]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

Same as split()

In [19]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

Depht-wise splitting

In [20]:
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### Array attributes

In [22]:
b = np.arange(24).reshape(2, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [27]:
b.dtype

dtype('int32')

ndim - number of dimensions

In [23]:
b.ndim

2

size - number of elements

In [24]:
b.size

24

itemsize - number of bytes for each element

In [25]:
b.itemsize

4

nbytes - total number of bytes the array requires

In [26]:
b.nbytes

96

### Array functions

In [29]:
b = np.array([1.+1.j, 3. + 2.j])
b

array([1.+1.j, 3.+2.j])

In [30]:
b.dtype

dtype('complex128')

convert to a list

In [31]:
b.tolist()

[(1+1j), (3+2j)]

convert to a specific type

In [33]:
a = np.array(4, dtype='int')
a

array(4)

In [34]:
a.dtype

dtype('int32')

In [35]:
a.astype(float)

array(4.)